name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Merge main into PR branch
        if: github.event_name == 'pull_request'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git fetch origin main
          if ! git merge origin/main; then
            echo "Merge failed due to conflicts. Please rebase your branch on main."
            exit 1
          fi

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Setup Nix cache
        uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          # don't keep caches from previous CI runs around. newest main should always be enough
          purge: true
          purge-prefixes: nix-${{ runner.os }}-
          purge-created: 0
          purge-primary-key: never

      - name: Run checks
        run: nix flake check --log-format bar-with-logs
